import React, {useState} from "react";
import { Container } from "react-bootstrap";
import { useAuth } from "../../Context/AuthContext";
import { headersForm, postRequest } from "../../utils/RequestHandler";


export default function Dashboard(props){

    const {currentUser} = useAuth();

    const [test,setTest] = useState("");
    const [file, setFile] = useState(null)


    const handleSubmit = async (e) => {
        e.preventDefault();
        const formdata = new FormData();
        formdata.append("file", file, file.name);
        formdata.append("test", test);

        const result = await postRequest("file/upload", formdata, true, headersForm);
        console.log(result);

    }

    const onFileChange = e => {
        setFile(e.target.files[0])
    }
    return(
        <Container>
            Hello from Admin Dashboard
            <form>
                <input value={test} type="text" name="test" onChange={e => setTest(e.target.value)} />
                <input type="file" name="file" onChange={onFileChange} />
                <button type="submit" onClick={handleSubmit}>Submit</button>
            </form>
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum pharetra dui ut vestibulum aliquam. Maecenas consequat lobortis convallis. Nulla sit amet nunc a sapien aliquam vestibulum at in eros. Vivamus ligula turpis, pharetra pretium vehicula sit amet, vehicula in ligula. Duis molestie sed mauris id bibendum. Suspendisse id dui elit. Sed aliquet massa in ultricies elementum. Praesent volutpat ante auctor augue accumsan sodales. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed in facilisis magna, at venenatis leo. Fusce auctor tellus vitae arcu lobortis, et fringilla ex consectetur. Vivamus viverra massa nulla. Donec non urna feugiat, bibendum metus a, facilisis odio. Nunc arcu odio, facilisis nec ex et, ultricies scelerisque diam. Nunc neque dui, placerat ut placerat nec, sollicitudin vitae erat.

Cras euismod ipsum ex, a molestie tellus ultricies a. Vestibulum maximus lacus ut nunc consequat consectetur. Etiam porta pellentesque lorem, at maximus ipsum porta quis. Donec efficitur mi magna, eget pharetra nisi tristique mollis. Aenean imperdiet rhoncus metus id gravida. Vestibulum tempus odio sed tellus cursus, et tincidunt risus consequat. Aliquam non placerat velit, at dignissim felis. Praesent sed lectus lorem. Fusce a velit consectetur, porttitor risus eu, auctor ante. Maecenas vel lectus quis neque blandit posuere. Cras ullamcorper cursus sem non laoreet. Pellentesque aliquet ornare leo, eget porttitor velit fringilla non. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi ornare at sapien ac condimentum.

Morbi id velit in ipsum varius hendrerit molestie non leo. Aliquam vulputate, nisi non malesuada fermentum, lorem velit pretium quam, vel dapibus nulla justo fermentum ipsum. Nullam fringilla vel nisi sit amet lobortis. Curabitur porttitor, urna in convallis euismod, arcu dui egestas purus, eget consectetur lectus libero sagittis purus. Maecenas placerat risus ligula. Nullam ultricies fringilla felis ut elementum. Curabitur eleifend est a lectus lacinia facilisis. Etiam sed hendrerit turpis. Sed tincidunt, metus vitae bibendum ornare, mi quam facilisis nisi, id sollicitudin lacus massa vel dui. Morbi semper eros a libero dignissim vehicula. Donec sagittis rutrum euismod. Phasellus vel sagittis purus, vitae consequat mauris. Morbi gravida tincidunt tincidunt.

Pellentesque sed nisi at tortor molestie molestie nec vel justo. Quisque dictum, augue quis vehicula elementum, augue quam convallis ipsum, et lobortis risus orci eu mi. Cras mattis, lorem vel rutrum rhoncus, dolor metus convallis massa, ac pellentesque dui nisi quis sapien. Phasellus ultricies turpis vitae odio consequat aliquam. Duis convallis, nunc vel eleifend venenatis, dolor diam vestibulum libero, quis porta enim quam a ipsum. Suspendisse vestibulum libero non malesuada condimentum. Vivamus sed posuere diam. Phasellus eleifend tellus quis nisl malesuada maximus. Aenean varius quam eu magna porta pharetra. Aliquam semper, justo vitae vestibulum blandit, urna purus rutrum tellus, a feugiat purus augue eu ex.

Proin et rhoncus enim, sed varius turpis. Donec pretium ultricies est, sed tristique neque faucibus a. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum pretium ante in erat sodales rhoncus non id massa. Quisque pretium et est non pulvinar. Aliquam pretium est eu dolor laoreet semper. Sed ac tortor vitae neque dapibus facilisis. Sed euismod lectus id ipsum porta dapibus condimentum vitae neque. Curabitur laoreet, dolor ac vehicula lacinia, ligula nibh cursus ante, non mattis eros nibh at odio. Donec imperdiet lectus eget pellentesque maximus. Nullam pharetra rhoncus est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum pharetra dui ut vestibulum aliquam. Maecenas consequat lobortis convallis. Nulla sit amet nunc a sapien aliquam vestibulum at in eros. Vivamus ligula turpis, pharetra pretium vehicula sit amet, vehicula in ligula. Duis molestie sed mauris id bibendum. Suspendisse id dui elit. Sed aliquet massa in ultricies elementum. Praesent volutpat ante auctor augue accumsan sodales. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed in facilisis magna, at venenatis leo. Fusce auctor tellus vitae arcu lobortis, et fringilla ex consectetur. Vivamus viverra massa nulla. Donec non urna feugiat, bibendum metus a, facilisis odio. Nunc arcu odio, facilisis nec ex et, ultricies scelerisque diam. Nunc neque dui, placerat ut placerat nec, sollicitudin vitae erat.

Cras euismod ipsum ex, a molestie tellus ultricies a. Vestibulum maximus lacus ut nunc consequat consectetur. Etiam porta pellentesque lorem, at maximus ipsum porta quis. Donec efficitur mi magna, eget pharetra nisi tristique mollis. Aenean imperdiet rhoncus metus id gravida. Vestibulum tempus odio sed tellus cursus, et tincidunt risus consequat. Aliquam non placerat velit, at dignissim felis. Praesent sed lectus lorem. Fusce a velit consectetur, porttitor risus eu, auctor ante. Maecenas vel lectus quis neque blandit posuere. Cras ullamcorper cursus sem non laoreet. Pellentesque aliquet ornare leo, eget porttitor velit fringilla non. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi ornare at sapien ac condimentum.

Morbi id velit in ipsum varius hendrerit molestie non leo. Aliquam vulputate, nisi non malesuada fermentum, lorem velit pretium quam, vel dapibus nulla justo fermentum ipsum. Nullam fringilla vel nisi sit amet lobortis. Curabitur porttitor, urna in convallis euismod, arcu dui egestas purus, eget consectetur lectus libero sagittis purus. Maecenas placerat risus ligula. Nullam ultricies fringilla felis ut elementum. Curabitur eleifend est a lectus lacinia facilisis. Etiam sed hendrerit turpis. Sed tincidunt, metus vitae bibendum ornare, mi quam facilisis nisi, id sollicitudin lacus massa vel dui. Morbi semper eros a libero dignissim vehicula. Donec sagittis rutrum euismod. Phasellus vel sagittis purus, vitae consequat mauris. Morbi gravida tincidunt tincidunt.

Pellentesque sed nisi at tortor molestie molestie nec vel justo. Quisque dictum, augue quis vehicula elementum, augue quam convallis ipsum, et lobortis risus orci eu mi. Cras mattis, lorem vel rutrum rhoncus, dolor metus convallis massa, ac pellentesque dui nisi quis sapien. Phasellus ultricies turpis vitae odio consequat aliquam. Duis convallis, nunc vel eleifend venenatis, dolor diam vestibulum libero, quis porta enim quam a ipsum. Suspendisse vestibulum libero non malesuada condimentum. Vivamus sed posuere diam. Phasellus eleifend tellus quis nisl malesuada maximus. Aenean varius quam eu magna porta pharetra. Aliquam semper, justo vitae vestibulum blandit, urna purus rutrum tellus, a feugiat purus augue eu ex.

Proin et rhoncus enim, sed varius turpis. Donec pretium ultricies est, sed tristique neque faucibus a. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum pretium ante in erat sodales rhoncus non id massa. Quisque pretium et est non pulvinar. Aliquam pretium est eu dolor laoreet semper. Sed ac tortor vitae neque dapibus facilisis. Sed euismod lectus id ipsum porta dapibus condimentum vitae neque. Curabitur laoreet, dolor ac vehicula lacinia, ligula nibh cursus ante, non mattis eros nibh at odio. Donec imperdiet lectus eget pellentesque maximus. Nullam pharetra rhoncus est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum pharetra dui ut vestibulum aliquam. Maecenas consequat lobortis convallis. Nulla sit amet nunc a sapien aliquam vestibulum at in eros. Vivamus ligula turpis, pharetra pretium vehicula sit amet, vehicula in ligula. Duis molestie sed mauris id bibendum. Suspendisse id dui elit. Sed aliquet massa in ultricies elementum. Praesent volutpat ante auctor augue accumsan sodales. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed in facilisis magna, at venenatis leo. Fusce auctor tellus vitae arcu lobortis, et fringilla ex consectetur. Vivamus viverra massa nulla. Donec non urna feugiat, bibendum metus a, facilisis odio. Nunc arcu odio, facilisis nec ex et, ultricies scelerisque diam. Nunc neque dui, placerat ut placerat nec, sollicitudin vitae erat.

Cras euismod ipsum ex, a molestie tellus ultricies a. Vestibulum maximus lacus ut nunc consequat consectetur. Etiam porta pellentesque lorem, at maximus ipsum porta quis. Donec efficitur mi magna, eget pharetra nisi tristique mollis. Aenean imperdiet rhoncus metus id gravida. Vestibulum tempus odio sed tellus cursus, et tincidunt risus consequat. Aliquam non placerat velit, at dignissim felis. Praesent sed lectus lorem. Fusce a velit consectetur, porttitor risus eu, auctor ante. Maecenas vel lectus quis neque blandit posuere. Cras ullamcorper cursus sem non laoreet. Pellentesque aliquet ornare leo, eget porttitor velit fringilla non. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi ornare at sapien ac condimentum.

Morbi id velit in ipsum varius hendrerit molestie non leo. Aliquam vulputate, nisi non malesuada fermentum, lorem velit pretium quam, vel dapibus nulla justo fermentum ipsum. Nullam fringilla vel nisi sit amet lobortis. Curabitur porttitor, urna in convallis euismod, arcu dui egestas purus, eget consectetur lectus libero sagittis purus. Maecenas placerat risus ligula. Nullam ultricies fringilla felis ut elementum. Curabitur eleifend est a lectus lacinia facilisis. Etiam sed hendrerit turpis. Sed tincidunt, metus vitae bibendum ornare, mi quam facilisis nisi, id sollicitudin lacus massa vel dui. Morbi semper eros a libero dignissim vehicula. Donec sagittis rutrum euismod. Phasellus vel sagittis purus, vitae consequat mauris. Morbi gravida tincidunt tincidunt.

Pellentesque sed nisi at tortor molestie molestie nec vel justo. Quisque dictum, augue quis vehicula elementum, augue quam convallis ipsum, et lobortis risus orci eu mi. Cras mattis, lorem vel rutrum rhoncus, dolor metus convallis massa, ac pellentesque dui nisi quis sapien. Phasellus ultricies turpis vitae odio consequat aliquam. Duis convallis, nunc vel eleifend venenatis, dolor diam vestibulum libero, quis porta enim quam a ipsum. Suspendisse vestibulum libero non malesuada condimentum. Vivamus sed posuere diam. Phasellus eleifend tellus quis nisl malesuada maximus. Aenean varius quam eu magna porta pharetra. Aliquam semper, justo vitae vestibulum blandit, urna purus rutrum tellus, a feugiat purus augue eu ex.

Proin et rhoncus enim, sed varius turpis. Donec pretium ultricies est, sed tristique neque faucibus a. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum pretium ante in erat sodales rhoncus non id massa. Quisque pretium et est non pulvinar. Aliquam pretium est eu dolor laoreet semper. Sed ac tortor vitae neque dapibus facilisis. Sed euismod lectus id ipsum porta dapibus condimentum vitae neque. Curabitur laoreet, dolor ac vehicula lacinia, ligula nibh cursus ante, non mattis eros nibh at odio. Donec imperdiet lectus eget pellentesque maximus. Nullam pharetra rhoncus est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum pharetra dui ut vestibulum aliquam. Maecenas consequat lobortis convallis. Nulla sit amet nunc a sapien aliquam vestibulum at in eros. Vivamus ligula turpis, pharetra pretium vehicula sit amet, vehicula in ligula. Duis molestie sed mauris id bibendum. Suspendisse id dui elit. Sed aliquet massa in ultricies elementum. Praesent volutpat ante auctor augue accumsan sodales. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed in facilisis magna, at venenatis leo. Fusce auctor tellus vitae arcu lobortis, et fringilla ex consectetur. Vivamus viverra massa nulla. Donec non urna feugiat, bibendum metus a, facilisis odio. Nunc arcu odio, facilisis nec ex et, ultricies scelerisque diam. Nunc neque dui, placerat ut placerat nec, sollicitudin vitae erat.

Cras euismod ipsum ex, a molestie tellus ultricies a. Vestibulum maximus lacus ut nunc consequat consectetur. Etiam porta pellentesque lorem, at maximus ipsum porta quis. Donec efficitur mi magna, eget pharetra nisi tristique mollis. Aenean imperdiet rhoncus metus id gravida. Vestibulum tempus odio sed tellus cursus, et tincidunt risus consequat. Aliquam non placerat velit, at dignissim felis. Praesent sed lectus lorem. Fusce a velit consectetur, porttitor risus eu, auctor ante. Maecenas vel lectus quis neque blandit posuere. Cras ullamcorper cursus sem non laoreet. Pellentesque aliquet ornare leo, eget porttitor velit fringilla non. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi ornare at sapien ac condimentum.

Morbi id velit in ipsum varius hendrerit molestie non leo. Aliquam vulputate, nisi non malesuada fermentum, lorem velit pretium quam, vel dapibus nulla justo fermentum ipsum. Nullam fringilla vel nisi sit amet lobortis. Curabitur porttitor, urna in convallis euismod, arcu dui egestas purus, eget consectetur lectus libero sagittis purus. Maecenas placerat risus ligula. Nullam ultricies fringilla felis ut elementum. Curabitur eleifend est a lectus lacinia facilisis. Etiam sed hendrerit turpis. Sed tincidunt, metus vitae bibendum ornare, mi quam facilisis nisi, id sollicitudin lacus massa vel dui. Morbi semper eros a libero dignissim vehicula. Donec sagittis rutrum euismod. Phasellus vel sagittis purus, vitae consequat mauris. Morbi gravida tincidunt tincidunt.

Pellentesque sed nisi at tortor molestie molestie nec vel justo. Quisque dictum, augue quis vehicula elementum, augue quam convallis ipsum, et lobortis risus orci eu mi. Cras mattis, lorem vel rutrum rhoncus, dolor metus convallis massa, ac pellentesque dui nisi quis sapien. Phasellus ultricies turpis vitae odio consequat aliquam. Duis convallis, nunc vel eleifend venenatis, dolor diam vestibulum libero, quis porta enim quam a ipsum. Suspendisse vestibulum libero non malesuada condimentum. Vivamus sed posuere diam. Phasellus eleifend tellus quis nisl malesuada maximus. Aenean varius quam eu magna porta pharetra. Aliquam semper, justo vitae vestibulum blandit, urna purus rutrum tellus, a feugiat purus augue eu ex.

Proin et rhoncus enim, sed varius turpis. Donec pretium ultricies est, sed tristique neque faucibus a. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum pretium ante in erat sodales rhoncus non id massa. Quisque pretium et est non pulvinar. Aliquam pretium est eu dolor laoreet semper. Sed ac tortor vitae neque dapibus facilisis. Sed euismod lectus id ipsum porta dapibus condimentum vitae neque. Curabitur laoreet, dolor ac vehicula lacinia, ligula nibh cursus ante, non mattis eros nibh at odio. Donec imperdiet lectus eget pellentesque maximus. Nullam pharetra rhoncus est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum pharetra dui ut vestibulum aliquam. Maecenas consequat lobortis convallis. Nulla sit amet nunc a sapien aliquam vestibulum at in eros. Vivamus ligula turpis, pharetra pretium vehicula sit amet, vehicula in ligula. Duis molestie sed mauris id bibendum. Suspendisse id dui elit. Sed aliquet massa in ultricies elementum. Praesent volutpat ante auctor augue accumsan sodales. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed in facilisis magna, at venenatis leo. Fusce auctor tellus vitae arcu lobortis, et fringilla ex consectetur. Vivamus viverra massa nulla. Donec non urna feugiat, bibendum metus a, facilisis odio. Nunc arcu odio, facilisis nec ex et, ultricies scelerisque diam. Nunc neque dui, placerat ut placerat nec, sollicitudin vitae erat.

Cras euismod ipsum ex, a molestie tellus ultricies a. Vestibulum maximus lacus ut nunc consequat consectetur. Etiam porta pellentesque lorem, at maximus ipsum porta quis. Donec efficitur mi magna, eget pharetra nisi tristique mollis. Aenean imperdiet rhoncus metus id gravida. Vestibulum tempus odio sed tellus cursus, et tincidunt risus consequat. Aliquam non placerat velit, at dignissim felis. Praesent sed lectus lorem. Fusce a velit consectetur, porttitor risus eu, auctor ante. Maecenas vel lectus quis neque blandit posuere. Cras ullamcorper cursus sem non laoreet. Pellentesque aliquet ornare leo, eget porttitor velit fringilla non. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi ornare at sapien ac condimentum.

Morbi id velit in ipsum varius hendrerit molestie non leo. Aliquam vulputate, nisi non malesuada fermentum, lorem velit pretium quam, vel dapibus nulla justo fermentum ipsum. Nullam fringilla vel nisi sit amet lobortis. Curabitur porttitor, urna in convallis euismod, arcu dui egestas purus, eget consectetur lectus libero sagittis purus. Maecenas placerat risus ligula. Nullam ultricies fringilla felis ut elementum. Curabitur eleifend est a lectus lacinia facilisis. Etiam sed hendrerit turpis. Sed tincidunt, metus vitae bibendum ornare, mi quam facilisis nisi, id sollicitudin lacus massa vel dui. Morbi semper eros a libero dignissim vehicula. Donec sagittis rutrum euismod. Phasellus vel sagittis purus, vitae consequat mauris. Morbi gravida tincidunt tincidunt.

Pellentesque sed nisi at tortor molestie molestie nec vel justo. Quisque dictum, augue quis vehicula elementum, augue quam convallis ipsum, et lobortis risus orci eu mi. Cras mattis, lorem vel rutrum rhoncus, dolor metus convallis massa, ac pellentesque dui nisi quis sapien. Phasellus ultricies turpis vitae odio consequat aliquam. Duis convallis, nunc vel eleifend venenatis, dolor diam vestibulum libero, quis porta enim quam a ipsum. Suspendisse vestibulum libero non malesuada condimentum. Vivamus sed posuere diam. Phasellus eleifend tellus quis nisl malesuada maximus. Aenean varius quam eu magna porta pharetra. Aliquam semper, justo vitae vestibulum blandit, urna purus rutrum tellus, a feugiat purus augue eu ex.

Proin et rhoncus enim, sed varius turpis. Donec pretium ultricies est, sed tristique neque faucibus a. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum pretium ante in erat sodales rhoncus non id massa. Quisque pretium et est non pulvinar. Aliquam pretium est eu dolor laoreet semper. Sed ac tortor vitae neque dapibus facilisis. Sed euismod lectus id ipsum porta dapibus condimentum vitae neque. Curabitur laoreet, dolor ac vehicula lacinia, ligula nibh cursus ante, non mattis eros nibh at odio. Donec imperdiet lectus eget pellentesque maximus. Nullam pharetra rhoncus est. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

            </p>
        </Container>
    )
}